apiVersion: v1
kind: Namespace
metadata:
  annotations:
    itlabs.io/certfetcher.example-certificate-secret-name: secret/path/to/secret/in/vault
  labels:
    itlabs.io/certfetcher: "true"
    kubernetes.io/metadata.name: default
  name: default